const courseModel = [
    {
      id: 1,
      name: 'Introduction to React Native',
      instructor: 'John Doe',
      description: 'Learn the basics of React Native development and build your first mobile app.',
      enrollmentStatus: 'Open',
      thumbnail: 'your.image.here',
      duration: '8 weeks',
      schedule: 'Tuesdays and Thursdays, 6:00 PM - 8:00 PM',
      location: 'Online',
      prerequisites: ['Basic JavaScript knowledge', 'Familiarity with React'],
      syllabus: [
        { week: 1, topic: 'Introduction to React Native', content: 'Overview of React Native, setting up your development environment.' },
        { week: 2, topic: 'Building Your First App', content: 'Creating a simple mobile app using React Native components.' },
      ],
      students: [
        { id: 101, name: 'Alice Johnson', email: 'alice@example.com' },
        { id: 102, name: 'Bob Smith', email: 'bob@example.com' },
      ],
    },
    {
      id: 2,
      name: 'Advanced JavaScript',
      instructor: 'Jane Smith',
      description: 'Deepen your understanding of JavaScript and its advanced features.',
      enrollmentStatus: 'Closed',
      thumbnail: 'your.image.here',
      duration: '10 weeks',
      schedule: 'Mondays and Wednesdays, 7:00 PM - 9:00 PM',
      location: 'Onsite',
      prerequisites: ['Intermediate JavaScript knowledge'],
      syllabus: [
        { week: 1, topic: 'Closures and Scope', content: 'Understanding closures and lexical scope in JavaScript.' },
        { week: 2, topic: 'Asynchronous JavaScript', content: 'Working with asynchronous code using callbacks, promises, and async/await.' },
      ],
      students: [
        { id: 201, name: 'Charlie Brown', email: 'charlie@example.com' },
        { id: 202, name: 'Diana Lee', email: 'diana@example.com' },
      ],
    },
    {
      id: 3,
      name: 'Web Development Bootcamp',
      instructor: 'Alex Johnson',
      description: 'Comprehensive course covering HTML, CSS, and JavaScript for web development.',
      enrollmentStatus: 'InProgress',
      thumbnail: 'your.image.here',
      duration: '12 weeks',
      schedule: 'Saturdays and Sundays, 10:00 AM - 2:00 PM',
      location: 'Online',
      prerequisites: ['No prerequisites'],
      syllabus: [
        { week: 1, topic: 'HTML Fundamentals', content: 'Learning the basics of HTML and structuring web pages.' },
        { week: 2, topic: 'CSS Styling', content: 'Styling web pages with CSS, including layout and design principles.' },
      ],
      students: [
        { id: 301, name: 'Eva Miller', email: 'eva@example.com' },
        { id: 302, name: 'Frank Wilson', email: 'frank@example.com' },
      ],
    },
    {
      id: 4,
      name: 'Data Science Essentials',
      instructor: 'Maria Rodriguez',
      description: 'Explore the fundamentals of data science and analysis.',
      enrollmentStatus: 'Open',
      thumbnail: 'your.image.here',
      duration: '6 weeks',
      schedule: 'Fridays, 4:00 PM - 6:00 PM',
      location: 'Online',
      prerequisites: ['Basic programming knowledge', 'Understanding of statistics'],
      syllabus: [
        { week: 1, topic: 'Introduction to Data Science', content: 'Overview of data science, tools, and applications.' },
        { week: 2, topic: 'Data Analysis with Python', content: 'Using Python for data analysis and visualization.' },
      ],
      students: [
        { id: 401, name: 'Grace Turner', email: 'grace@example.com' },
        { id: 402, name: 'Henry White', email: 'henry@example.com' },
      ],
    },
    {
      id: 5,
      name: 'Mobile App Design',
      instructor: 'Sophia Martinez',
      description: 'Learn principles of mobile app design and user experience.',
      enrollmentStatus: 'Open',
      thumbnail: 'your.image.here',
      duration: '8 weeks',
      schedule: 'Wednesdays, 5:00 PM - 7:00 PM',
      location: 'Online',
      prerequisites: ['Basic design knowledge', 'Familiarity with UI/UX concepts'],
      syllabus: [
        { week: 1, topic: 'UI Design Basics', content: 'Introduction to user interface design principles.' },
        { week: 2, topic: 'Mobile App Wireframing', content: 'Creating wireframes for mobile applications.' },
      ],
      students: [
        { id: 501, name: 'Isaac Turner', email: 'isaac@example.com' },
        { id: 502, name: 'Jessica Davis', email: 'jessica@example.com' },
      ],
    },
    {
        id: 6,
        name: 'Python for Beginners',
        instructor: 'Michael Turner',
        description: 'Get started with Python programming language from scratch.',
        enrollmentStatus: 'Open',
        thumbnail: 'your.image.here',
        duration: '6 weeks',
        schedule: 'Mondays and Thursdays, 7:00 PM - 9:00 PM',
        location: 'Online',
        prerequisites: ['No prerequisites'],
        syllabus: [
          { week: 1, topic: 'Introduction to Python', content: 'Overview of Python and basic syntax.' },
          { week: 2, topic: 'Data Structures in Python', content: 'Working with lists, tuples, and dictionaries.' },
        ],
        students: [
          { id: 601, name: 'Karen Brown', email: 'karen@example.com' },
          { id: 602, name: 'Leo Johnson', email: 'leo@example.com' },
        ],
      },
      {
        id: 7,
        name: 'Machine Learning Fundamentals',
        instructor: 'Emily Davis',
        description: 'An introduction to machine learning algorithms and applications.',
        enrollmentStatus: 'Closed',
        thumbnail: 'your.image.here',
        duration: '10 weeks',
        schedule: 'Tuesdays and Fridays, 6:00 PM - 8:00 PM',
        location: 'Onsite',
        prerequisites: ['Understanding of basic statistics', 'Programming knowledge'],
        syllabus: [
          { week: 1, topic: 'Introduction to Machine Learning', content: 'Overview of machine learning concepts.' },
          { week: 2, topic: 'Supervised Learning', content: 'Understanding supervised learning algorithms.' },
        ],
        students: [
          { id: 701, name: 'Mia Wilson', email: 'mia@example.com' },
          { id: 702, name: 'Nathan Turner', email: 'nathan@example.com' },
        ],
      },
      
      {
        id: 8,
        name: 'Full Stack Web Development',
        instructor: 'David Miller',
        description: 'Master the art of full-stack web development with modern technologies.',
        enrollmentStatus: 'Open',
        thumbnail: 'your.image.here',
        duration: '12 weeks',
        schedule: 'Saturdays and Sundays, 10:00 AM - 2:00 PM',
        location: 'Online',
        prerequisites: ['Basic HTML, CSS, and JavaScript knowledge'],
        syllabus: [
          { week: 1, topic: 'Introduction to Full Stack', content: 'Overview of full-stack development and architecture.' },
          { week: 2, topic: 'Frontend Development', content: 'Building interactive user interfaces with React.' },
        ],
        students: [
          { id: 2001, name: 'Olivia Taylor', email: 'olivia@example.com' },
          { id: 2002, name: 'Peter Smith', email: 'peter@example.com' },
        ],
      },
  ];
  
  export default courseModel;
  