const courseModel = [
    {
      id: 1,
      name: 'Introduction to React Native',
      instructor: 'John Doe',
      description: 'Learn the basics of React Native development and build your first mobile app.',
      enrollmentStatus: 'Open',
      thumbnail: 'your.image.here',
      duration: '8 weeks',
      schedule: 'Tuesdays and Thursdays, 6:00 PM - 8:00 PM',
      location: 'Online',
      prerequisites: ['Basic JavaScript knowledge', 'Familiarity with React'],
      syllabus: [
        { week: 1, topic: 'Introduction to React Native', content: 'Overview of React Native, setting up your development environment.' },
        { week: 2, topic: 'Building Your First App', content: 'Creating a simple mobile app using React Native components.' },
      ],
      students: [
        { id: 101, name: 'Alice Johnson', email: 'alice@example.com' },
        { id: 102, name: 'Bob Smith', email: 'bob@example.com' },
      ],
    },
    {
      id: 2,
      name: 'Advanced JavaScript',
      instructor: 'Jane Smith',
      description: 'Deepen your understanding of JavaScript and its advanced features.',
      enrollmentStatus: 'Closed',
      thumbnail: 'your.image.here',
      duration: '10 weeks',
      schedule: 'Mondays and Wednesdays, 7:00 PM - 9:00 PM',
      location: 'Onsite',
      prerequisites: ['Intermediate JavaScript knowledge'],
      syllabus: [
        { week: 1, topic: 'Closures and Scope', content: 'Understanding closures and lexical scope in JavaScript.' },
        { week: 2, topic: 'Asynchronous JavaScript', content: 'Working with asynchronous code using callbacks, promises, and async/await.' },
      ],
      students: [
        { id: 201, name: 'Charlie Brown', email: 'charlie@example.com' },
        { id: 202, name: 'Diana Lee', email: 'diana@example.com' },
      ],
    },
    {
      id: 3,
      name: 'Web Development Bootcamp',
      instructor: 'Alex Johnson',
      description: 'Comprehensive course covering HTML, CSS, and JavaScript for web development.',
      enrollmentStatus: 'InProgress',
      thumbnail: 'your.image.here',
      duration: '12 weeks',
      schedule: 'Saturdays and Sundays, 10:00 AM - 2:00 PM',
      location: 'Online',
      prerequisites: ['No prerequisites'],
      syllabus: [
        { week: 1, topic: 'HTML Fundamentals', content: 'Learning the basics of HTML and structuring web pages.' },
        { week: 2, topic: 'CSS Styling', content: 'Styling web pages with CSS, including layout and design principles.' },
      ],
      students: [
        { id: 301, name: 'Eva Miller', email: 'eva@example.com' },
        { id: 302, name: 'Frank Wilson', email: 'frank@example.com' },
      ],
    },
    {
      id: 4,
      name: 'Data Science Essentials',
      instructor: 'Maria Rodriguez',
      description: 'Explore the fundamentals of data science and analysis.',
      enrollmentStatus: 'Open',
      thumbnail: 'your.image.here',
      duration: '6 weeks',
      schedule: 'Fridays, 4:00 PM - 6:00 PM',
      location: 'Online',
      prerequisites: ['Basic programming knowledge', 'Understanding of statistics'],
      syllabus: [
        { week: 1, topic: 'Introduction to Data Science', content: 'Overview of data science, tools, and applications.' },
        { week: 2, topic: 'Data Analysis with Python', content: 'Using Python for data analysis and visualization.' },
      ],
      students: [
        { id: 401, name: 'Grace Turner', email: 'grace@example.com' },
        { id: 402, name: 'Henry White', email: 'henry@example.com' },
      ],
    },
    {
      id: 5,
      name: 'Mobile App Design',
      instructor: 'Sophia Martinez',
      description: 'Learn principles of mobile app design and user experience.',
      enrollmentStatus: 'Open',
      thumbnail: 'your.image.here',
      duration: '8 weeks',
      schedule: 'Wednesdays, 5:00 PM - 7:00 PM',
      location: 'Online',
      prerequisites: ['Basic design knowledge', 'Familiarity with UI/UX concepts'],
      syllabus: [
        { week: 1, topic: 'UI Design Basics', content: 'Introduction to user interface design principles.' },
        { week: 2, topic: 'Mobile App Wireframing', content: 'Creating wireframes for mobile applications.' },
      ],
      students: [
        { id: 501, name: 'Isaac Turner', email: 'isaac@example.com' },
        { id: 502, name: 'Jessica Davis', email: 'jessica@example.com' },
      ],
    },
    {
        id: 6,
        name: 'Python for Beginners',
        instructor: 'Michael Turner',
        description: 'Get started with Python programming language from scratch.',
        enrollmentStatus: 'Open',
        thumbnail: 'your.image.here',
        duration: '6 weeks',
        schedule: 'Mondays and Thursdays, 7:00 PM - 9:00 PM',
        location: 'Online',
        prerequisites: ['No prerequisites'],
        syllabus: [
          { week: 1, topic: 'Introduction to Python', content: 'Overview of Python and basic syntax.' },
          { week: 2, topic: 'Data Structures in Python', content: 'Working with lists, tuples, and dictionaries.' },
        ],
        students: [
          { id: 601, name: 'Karen Brown', email: 'karen@example.com' },
          { id: 602, name: 'Leo Johnson', email: 'leo@example.com' },
        ],
      },
      {
        id: 7,
        name: 'Machine Learning Fundamentals',
        instructor: 'Emily Davis',
        description: 'An introduction to machine learning algorithms and applications.',
        enrollmentStatus: 'Closed',
        thumbnail: 'your.image.here',
        duration: '10 weeks',
        schedule: 'Tuesdays and Fridays, 6:00 PM - 8:00 PM',
        location: 'Onsite',
        prerequisites: ['Understanding of basic statistics', 'Programming knowledge'],
        syllabus: [
          { week: 1, topic: 'Introduction to Machine Learning', content: 'Overview of machine learning concepts.' },
          { week: 2, topic: 'Supervised Learning', content: 'Understanding supervised learning algorithms.' },
        ],
        students: [
          { id: 701, name: 'Mia Wilson', email: 'mia@example.com' },
          { id: 702, name: 'Nathan Turner', email: 'nathan@example.com' },
        ],
      },
      
      {
        id: 8,
        name: 'Full Stack Web Development',
        instructor: 'David Miller',
        description: 'Master the art of full-stack web development with modern technologies.',
        enrollmentStatus: 'Open',
        thumbnail: 'your.image.here',
        duration: '12 weeks',
        schedule: 'Saturdays and Sundays, 10:00 AM - 2:00 PM',
        location: 'Online',
        prerequisites: ['Basic HTML, CSS, and JavaScript knowledge'],
        syllabus: [
          { week: 1, topic: 'Introduction to Full Stack', content: 'Overview of full-stack development and architecture.' },
          { week: 2, topic: 'Frontend Development', content: 'Building interactive user interfaces with React.' },
        ],
        students: [
          { id: 2001, name: 'Olivia Taylor', email: 'olivia@example.com' },
          { id: 2002, name: 'Peter Smith', email: 'peter@example.com' },
        ],
      },
      {
        id: 9,
        name: 'Machine Learning Foundations',
        instructor: 'William Adams',
        description: 'Learn the fundamentals of machine learning and its applications.',
        enrollmentStatus: 'Open',
        thumbnail: 'your.image.here',
        duration: '12 weeks',
        schedule: 'Tuesdays and Thursdays, 6:00 PM - 8:00 PM',
        location: 'Online',
        prerequisites: ['Basic Python programming knowledge', 'Linear algebra basics'],
        syllabus: [
          { week: 1, topic: 'Introduction to Machine Learning', content: 'Overview of machine learning concepts and applications.' },
          { week: 2, topic: 'Supervised Learning', content: 'Understanding supervised learning algorithms.' },
        ],
        students: [
          { id: 901, name: 'Sophie Harris', email: 'sophie@example.com' },
          { id: 902, name: 'Tom Clark', email: 'tom@example.com' },
        ],
      },
      {
        id: 10,
        name: 'React Native App Development',
        instructor: 'Alex Miller',
        description: 'Build cross-platform mobile apps with React Native.',
        enrollmentStatus: 'Open',
        thumbnail: 'your.image.here',
        duration: '8 weeks',
        schedule: 'Mondays and Wednesdays, 7:00 PM - 9:00 PM',
        location: 'Online',
        prerequisites: ['Familiarity with React', 'JavaScript knowledge'],
        syllabus: [
          { week: 1, topic: 'Introduction to React Native', content: 'Getting started with React Native and its architecture.' },
          { week: 2, topic: 'Navigation and State Management', content: 'Handling navigation and state in React Native apps.' },
        ],
        students: [
          { id: 1001, name: 'Emma White', email: 'emma@example.com' },
          { id: 1002, name: 'Liam Johnson', email: 'liam@example.com' },
        ],
      },
      {
        id: 11,
        name: 'Full Stack Web Development',
        instructor: 'Grace Wilson',
        description: 'Become a full-stack web developer with this comprehensive course.',
        enrollmentStatus: 'Closed',
        thumbnail: 'your.image.here',
        duration: '16 weeks',
        schedule: 'Saturdays and Sundays, 10:00 AM - 2:00 PM',
        location: 'Onsite',
        prerequisites: ['Basic HTML, CSS, and JavaScript knowledge'],
        syllabus: [
          { week: 1, topic: 'Frontend Development Basics', content: 'Introduction to HTML, CSS, and JavaScript.' },
          { week: 2, topic: 'Backend Development with Node.js', content: 'Building server-side applications with Node.js.' },
        ],
        students: [
          { id: 1101, name: 'Noah Anderson', email: 'noah@example.com' },
          { id: 1102, name: 'Ava Davis', email: 'ava@example.com' },
        ],
      },
      {
        id: 12,
        name: 'Artificial Intelligence Fundamentals',
        instructor: 'Lucy Martinez',
        description: 'Explore the fundamentals of artificial intelligence and its real-world applications.',
        enrollmentStatus: 'Open',
        thumbnail: 'your.image.here',
        duration: '10 weeks',
        schedule: 'Tuesdays and Thursdays, 6:00 PM - 8:00 PM',
        location: 'Online',
        prerequisites: ['Basic Python programming knowledge', 'Mathematics basics'],
        syllabus: [
          { week: 1, topic: 'Introduction to AI', content: 'Overview of artificial intelligence and its history.' },
          { week: 2, topic: 'Machine Learning Techniques', content: 'Understanding various machine learning techniques.' },
        ],
        students: [
          { id: 1201, name: 'Logan Garcia', email: 'logan@example.com' },
          { id: 1202, name: 'Chloe Robinson', email: 'chloe@example.com' },
        ],
      },
      {
        id: 13,
        name: 'Mobile App Design',
        instructor: 'Ethan Harris',
        description: 'Learn the principles of mobile app design and user experience.',
        enrollmentStatus: 'Open',
        thumbnail: 'your.image.here',
        duration: '8 weeks',
        schedule: 'Wednesdays, 5:00 PM - 7:00 PM',
        location: 'Online',
        prerequisites: ['Basic design principles'],
        syllabus: [
          { week: 1, topic: 'Introduction to Mobile Design', content: 'Understanding the unique challenges of mobile design.' },
          { week: 2, topic: 'UI/UX Principles', content: 'Exploring user interface and user experience design principles.' },
        ],
        students: [
          { id: 1301, name: 'Mia Turner', email: 'mia@example.com' },
          { id: 1302, name: 'Jackson Miller', email: 'jackson@example.com' },
        ],
      },
      {
        id: 14,
        name: 'Node.js Backend Development',
        instructor: 'Lily Wilson',
        description: 'Build scalable and efficient server-side applications with Node.js.',
        enrollmentStatus: 'InProgress',
        thumbnail: 'your.image.here',
        duration: '12 weeks',
        schedule: 'Thursdays, 7:00 PM - 9:00 PM',
        location: 'Online',
        prerequisites: ['JavaScript and asynchronous programming knowledge'],
        syllabus: [
          { week: 1, topic: 'Introduction to Node.js', content: 'Understanding the basics of Node.js and its event-driven architecture.' },
          { week: 2, topic: 'Express.js Framework', content: 'Building web applications with the Express.js framework.' },
        ],
        students: [
          { id: 1401, name: 'Jackie Adams', email: 'jackie@example.com' },
          { id: 1402, name: 'Henry Brown', email: 'henry@example.com' },
        ],
      },
      {
        id: 15,
        name: 'Frontend Web Development with React',
        instructor: 'Olivia Robinson',
        description: 'Master frontend web development using the React.js library.',
        enrollmentStatus: 'Open',
        thumbnail: 'your.image.here',
        duration: '10 weeks',
        schedule: 'Mondays and Wednesdays, 6:00 PM - 8:00 PM',
        location: 'Online',
        prerequisites: ['Basic HTML, CSS, and JavaScript knowledge'],
        syllabus: [
          { week: 1, topic: 'Introduction to React.js', content: 'Understanding the fundamentals of React.js.' },
          { week: 2, topic: 'Component-Based Development', content: 'Building modular and reusable components.' },
        ],
        students: [
          { id: 1501, name: 'Sophia Turner', email: 'sophia@example.com' },
          { id: 1502, name: 'James Carter', email: 'james@example.com' },
        ],
      },
      {
        id: 16,
        name: 'Java Programming Essentials',
        instructor: 'Christopher Davis',
        description: 'Learn the essentials of Java programming language for building robust applications.',
        enrollmentStatus: 'Open',
        thumbnail: 'your.image.here',
        duration: '12 weeks',
        schedule: 'Tuesdays and Thursdays, 7:00 PM - 9:00 PM',
        location: 'Online',
        prerequisites: ['No prerequisites'],
        syllabus: [
          { week: 1, topic: 'Introduction to Java', content: 'Overview of Java programming language and its syntax.' },
          { week: 2, topic: 'Object-Oriented Programming in Java', content: 'Understanding OOP concepts in Java.' },
        ],
        students: [
          { id: 1601, name: 'Aiden White', email: 'aiden@example.com' },
          { id: 1602, name: 'Ella Brown', email: 'ella@example.com' },
        ],
      },
      {
        id: 17,
        name: 'Cloud Computing Fundamentals',
        instructor: 'William Turner',
        description: 'Explore the basics of cloud computing and popular cloud platforms.',
        enrollmentStatus: 'Open',
        thumbnail: 'your.image.here',
        duration: '8 weeks',
        schedule: 'Wednesdays, 6:00 PM - 8:00 PM',
        location: 'Online',
        prerequisites: ['Basic computer knowledge'],
        syllabus: [
          { week: 1, topic: 'Introduction to Cloud Computing', content: 'Overview of cloud computing and its advantages.' },
          { week: 2, topic: 'Cloud Service Models', content: 'Understanding Infrastructure as a Service (IaaS), Platform as a Service (PaaS), and Software as a Service (SaaS).' },
        ],
        students: [
          { id: 1701, name: 'Gabriel Smith', email: 'gabriel@example.com' },
          { id: 1702, name: 'Aria Miller', email: 'aria@example.com' },
        ],
      },
      {
        id: 18,
        name: 'UI/UX Design Principles',
        instructor: 'Eva Davis',
        description: 'Master the principles of user interface and user experience design.',
        enrollmentStatus: 'Open',
        thumbnail: 'your.image.here',
        duration: '10 weeks',
        schedule: 'Thursdays, 6:00 PM - 8:00 PM',
        location: 'Online',
        prerequisites: ['No prerequisites'],
        syllabus: [
          { week: 1, topic: 'Introduction to UI/UX Design', content: 'Understanding the role of UI/UX in product development.' },
          { week: 2, topic: 'User Research and Prototyping', content: 'Conducting user research and creating prototypes.' },
        ],
        students: [
          { id: 1801, name: 'Carter Wilson', email: 'carter@example.com' },
          { id: 1802, name: 'Luna Turner', email: 'luna@example.com' },
        ],
      },
      {
        id: 19,
        name: 'Blockchain Basics',
        instructor: 'Leo Robinson',
        description: 'Explore the fundamentals of blockchain technology and its applications.',
        enrollmentStatus: 'InProgress',
        thumbnail: 'your.image.here',
        duration: '8 weeks',
        schedule: 'Mondays and Wednesdays, 6:30 PM - 8:30 PM',
        location: 'Online',
        prerequisites: ['Basic understanding of cryptography'],
        syllabus: [
          { week: 1, topic: 'Introduction to Blockchain', content: 'Overview of blockchain technology and its decentralized nature.' },
          { week: 2, topic: 'Cryptocurrencies and Smart Contracts', content: 'Understanding cryptocurrencies and creating smart contracts.' },
        ],
        students: [
          { id: 1901, name: 'Hudson White', email: 'hudson@example.com' },
          { id: 1902, name: 'Stella Davis', email: 'stella@example.com' },
        ],
      },
      {
        id: 20,
        name: 'Angular Framework Deep Dive',
        instructor: 'Victoria Smith',
        description: 'Dive deep into the Angular framework for building dynamic web applications.',
        enrollmentStatus: 'Open',
        thumbnail: 'your.image.here',
        duration: '12 weeks',
        schedule: 'Tuesdays and Thursdays, 6:30 PM - 8:30 PM',
        location: 'Online',
        prerequisites: ['Basic knowledge of HTML, CSS, and JavaScript'],
        syllabus: [
          { week: 1, topic: 'Introduction to Angular', content: 'Overview of Angular framework and its key features.' },
          { week: 2, topic: 'Components and Services', content: 'Understanding Angular components and services.' },
        ],
        students: [
          { id: 2001, name: 'Nathan Brown', email: 'nathan@example.com' },
          { id: 2002, name: 'Scarlett Turner', email: 'scarlett@example.com' },
        ],
      },
  ];
  
  export default courseModel;
  